export const articledata = [
    {
        index:"1-1", 
        image:"1.jpg",
        label:"Label",
        head:"Chef ok Yotam Ottolenghi’s London Test Kitchen Is Pure Joy",
        content:"It’s the second iteration of his culinary office",
        cname:"bloghead blogheada1",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"1-2",
        image:"1.jpg",
        label:"Nostalgia Alert",
        head:"If History Has Taught Us Anything, the Check Pattern Is Here to Stay",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada2",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"1-3",
        image:"1.jpg",
        label:"Label",
        head:"If History Has Taught Us Anything, the Check Pattern Is Here to Stay",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada3",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"1-4",
        image:"1.jpg",
        label:"Label",
        head:"If History Has Taught Us Anything, the Check Pattern Is Here to Stay",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada4",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"1-5",
        image:"1.jpg",
        label:"Label",
        head:"If History Has Taught Us Anything, the Check Pattern Is Here to Stay",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada5",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"2-1",
        image:"1.jpg",
        label:"Label",
        head:"Chef Yotam Ottolenghi’s London Test Kitchen Is Pure Joy",
        content:"It’s the second iteration of his culinary office",
        cname:"bloghead blogheada1",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"2-2",
        image:"1.jpg",
        label:"Nostalgia Alert",
        head:"If History Has Taught Us Anything, the Check Pattern Is Here to Stay",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada2",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"2-3",
        image:"1.jpg",
        label:"Label",
        head:"If History Has Taught Us Anything, the Check Pattern Is Here to Stay",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada3",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"2-4",
        image:"1.jpg",
        label:"Label",
        head:"If History Has Taught Us Anything, the Check Pattern Is Here to Stay",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada4",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"2-5",
        image:"1.jpg",
        label:"Label",
        head:"If History Has Taught Us Anything, the Check Pattern Is Here to Stay",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada5",
        category:"ARCHITECTURE + DESIGN",
        author:"Kristi Kellogg",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"3-1",
        category:"ADaITaYOURSELF",
        head:"5 Ideas to Steal From This Enchanting Dining Room",
        author:"Sophia Herring",
        image:"2.jpg",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada5",
        label:"Label",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"3-2",
        category:"ARCHITECTURE + DESIGN",
        head:"Inside Fear of God's Starkly Sensual New Downtown Los Angeles HQ",
        author:"Max Berlinger",
        image:"2.jpg",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada5",
        label:"Label",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    },
    {
        index:"3-3",
        category:"CLEVER",
        head:"25 Best Artificial Christmas Trees of 2021",
        author:"Kristi Kellogg",
        image:"2.jpg",
        content:"29 refreshing ways to channel the checkerboard in your own space",
        cname:"bloghead blogheada5",
        label:"Label",
        date: "13/01/2022",
        main: "All products featured on Architectural Digest are independently selected by our editors. However, when you buy something through our retail links, we may earn an affiliate commission.AD presents the Clever Guest Edit, a shopping series in which our favorite design enthusiasts share the products and collectibles that bring their homes to life. This week’s special guest is Brett Heyman, the founder of Edie Parker and Flower. Get the exclusive on what’s at the top of her wish list here and don’t forget to subscribe to the Clever newsletter to get these picks delivered straight to your inbox each month.Some might say that Brett Heyman has a special touch when it comes to curating a sensory experience. As the founder of fashion and accessories brands Edie Parker and Flower, she has a knack for setting a fun vibe to be enjoyed by any and everyone. Channeling everything from stars like Mary Tyler Moore to the Memphis Milano movement, Brett is always taking cues from the trailblazers that came before her and finding innovative ways to marry all of her inspirations through collections that feature an array of acrylic accessories.Brett is very intentional about how vignettes connect within the interiors of a space, down to the sconce on the wall or a luxury good that has a specific scent when you waltz into a room. “What I try to achieve is Gio Ponti meets Gloria Vanderbilt, so I love this ’70s, very Italian aesthetic,” she explains. “I like vintage pieces, but always with a sense of kookiness.”Brett’s mantra is to live with a sense of irreverence at home, so she’s a big fan of mismatching everything from colors and patterns to textures and materials. Vibrant things always catch her eye, but nothing too serious—the weirder it is, the better. Here, the entrepreneur shares 11 items that literally spark her joy."
    }
];